In [1]:
import pandas as pd
from datetime import date

In [2]:
def getthecounts(df,thecountry, todays_date):
    dfartists = df[["main_artist", "track_name", "rank", "IsGirlGroup", "IsBoyGroup", "IsMixedGroup", "End Date", "artistAppearanceCount"]]

    dfgroupstatus = df[["main_artist", "IsGirlGroup", "IsBoyGroup", "IsMixedGroup"]].drop_duplicates()
    dfgroupstatus.columns = ["main_artist", "IsGirlGroup_"+thecountry, "IsBoyGroup_"+thecountry, "IsMixedGroup_"+thecountry]

    dfnumenddates = dfartists[["main_artist", "End Date"]].drop_duplicates()
    
    dfnumenddates1 = pd.DataFrame(dfnumenddates.groupby(["main_artist"])["End Date"].count())
    dfnumenddates1 = dfnumenddates1.reset_index()
    dfnumenddates1.columns = ["main_artist", "#_dates_"+thecountry]

    dfjusttracks = dfartists[["main_artist", "track_name"]].drop_duplicates()

    dfcounttracks = pd.DataFrame(dfjusttracks.groupby(["main_artist"])["track_name"].count())
    dfcounttracks = dfcounttracks.reset_index()
    dfcounttracks.columns = ["main_artist", "#_songs_"+thecountry]

    dfjustranks = dfartists[["main_artist", "rank"]].drop_duplicates()
    dfjustranks_min = pd.DataFrame(dfjustranks.groupby(["main_artist"])["rank"].min())
    dfjustranks_max = pd.DataFrame(dfjustranks.groupby(["main_artist"])["rank"].max())
    
    dfjustranks_min = dfjustranks_min.reset_index()
    dfjustranks_min.columns = ["main_artist", "min_rank_"+thecountry]
    
    dfjustranks_max = dfjustranks_max.reset_index()
    dfjustranks_max.columns = ["main_artist", "max_rank_"+thecountry]

    dfartists["EndDate_Year_"+thecountry] = dfartists["End Date"].apply(lambda x : x.split("-")[0])
    dfartists["EndDate_Month_"+thecountry] = dfartists["End Date"].apply(lambda x : x.split("-")[1])
    dfartists["EndDate_Day_"+thecountry] = dfartists["End Date"].apply(lambda x : x.split("-")[2])
    dfartists["EndDate_Year_"+thecountry] = dfartists["EndDate_Year_"+thecountry].astype(int)
    dfartists["EndDate_Month_"+thecountry] = dfartists["EndDate_Month_"+thecountry].astype(int)
    dfartists["EndDate_Day_"+thecountry] = dfartists["EndDate_Day_"+thecountry].astype(int)

    df_EndDate_Yearthecountry = pd.DataFrame(dfartists.groupby(["main_artist"])["EndDate_Year_"+thecountry].min())
    df_EndDate_Yearthecountry = df_EndDate_Yearthecountry.reset_index()
    df_EndDate_Yearthecountry.columns = ["main_artist", "MinEndDate_Year_"+thecountry]
    df_EndDate_Monththecountry = pd.DataFrame(dfartists.groupby(["main_artist"])["EndDate_Month_"+thecountry].min())
    df_EndDate_Monththecountry = df_EndDate_Monththecountry.reset_index()
    df_EndDate_Monththecountry.columns = ["main_artist", "MinEndDate_Month_"+thecountry]
    df_EndDate_Daythecountry = pd.DataFrame(dfartists.groupby(["main_artist"])["EndDate_Day_"+thecountry].min())
    df_EndDate_Daythecountry = df_EndDate_Daythecountry.reset_index()
    df_EndDate_Daythecountry.columns = ["main_artist", "MinEndDate_Day_"+thecountry]
    df_EndDate_YearMonththecountry = df_EndDate_Yearthecountry.merge(df_EndDate_Monththecountry, left_on=["main_artist"], right_on=["main_artist"], how="inner")
    df_EndDate_YearMonthDaythecountryMin = df_EndDate_YearMonththecountry.merge(df_EndDate_Daythecountry, left_on=["main_artist"], right_on=["main_artist"], how="inner")
    

    df_EndDate_YearthecountryMax = pd.DataFrame(dfartists.groupby(["main_artist"])["EndDate_Year_"+thecountry].max())
    df_EndDate_YearthecountryMax = df_EndDate_YearthecountryMax.reset_index()
    df_EndDate_YearthecountryMax.columns = ["main_artist", "MaxEndDate_Year_"+thecountry]
    df_EndDate_MonththecountryMax = pd.DataFrame(dfartists.groupby(["main_artist"])["EndDate_Month_"+thecountry].max())
    df_EndDate_MonththecountryMax = df_EndDate_MonththecountryMax.reset_index()
    df_EndDate_MonththecountryMax.columns = ["main_artist", "MaxEndDate_Month_"+thecountry]
    df_EndDate_DaythecountryMax = pd.DataFrame(dfartists.groupby(["main_artist"])["EndDate_Day_"+thecountry].max())
    df_EndDate_DaythecountryMax = df_EndDate_DaythecountryMax.reset_index()
    df_EndDate_DaythecountryMax.columns = ["main_artist", "MaxEndDate_Day_"+thecountry]
    df_EndDate_YearMonththecountryMax = df_EndDate_YearthecountryMax.merge(df_EndDate_MonththecountryMax, left_on=["main_artist"], right_on=["main_artist"], how="inner")
    df_EndDate_YearMonthDaythecountryMaxDay = df_EndDate_YearMonththecountryMax.merge(df_EndDate_DaythecountryMax, left_on=["main_artist"], right_on=["main_artist"], how="inner")
    
    dfartists["EndDateDt_"+thecountry] = dfartists[["EndDate_Year_"+thecountry, "EndDate_Month_"+thecountry, "EndDate_Day_"+thecountry]].apply(lambda x : date(x["EndDate_Year_"+thecountry], x["EndDate_Month_"+thecountry], x["EndDate_Day_"+thecountry]), axis=1)
    dfearliest = pd.DataFrame(dfartists[["main_artist", "EndDateDt_"+thecountry]].groupby(["main_artist"])["EndDateDt_"+thecountry].min())
    dfearliest = dfearliest.reset_index()
    dfearliest.columns = ["main_artist", "Earliest_EndDateDt_"+thecountry]
    dfearliest["Longest_Charting_TimeDays_"+thecountry] = dfearliest["Earliest_EndDateDt_"+thecountry].apply(lambda x : (todays_date - x).days)
    dflatest = pd.DataFrame(dfartists[["main_artist", "EndDateDt_"+thecountry]].groupby(["main_artist"])["EndDateDt_"+thecountry].max())
    dflatest = dflatest.reset_index()
    dflatest.columns = ["main_artist", "Latest_EndDateDt_"+thecountry]
    dflatest["Shortest_Charting_TimeDays_"+thecountry] = dflatest["Latest_EndDateDt_"+thecountry].apply(lambda x : (todays_date - x).days)
    dftimes = dfearliest.merge(dflatest, left_on=["main_artist"], right_on=["main_artist"], how="inner")

    dfartistsfirstdate = dfartists[dfartists.artistAppearanceCount==0][["main_artist", "rank"]]
    dfartistsfirstdate.columns = ["main_artist", "first_artist_rank_"+thecountry]

    dfallranks = dfjustranks_max.merge(dfjustranks_min, left_on=["main_artist"], right_on=["main_artist"], how="inner")
    dfcounttracksranks = dfallranks.merge(dfcounttracks, left_on=["main_artist"], right_on=["main_artist"], how="inner")
    dfcounttracksranksnumenddates = dfcounttracksranks.merge(dfnumenddates1, left_on=["main_artist"], right_on=["main_artist"], how="inner")
    dfcounttracksranksnumenddatesgrp = dfcounttracksranksnumenddates.merge(dfgroupstatus, left_on=["main_artist"], right_on=["main_artist"], how="inner")
    dfcounttracksranksnumenddatesgrptimes = dfcounttracksranksnumenddatesgrp.merge(dftimes, left_on=["main_artist"], right_on=["main_artist"], how="inner")
    dfcounttracksranksnumenddatesgrptimesYear = dfcounttracksranksnumenddatesgrptimes.merge(df_EndDate_YearMonthDaythecountryMin, left_on=["main_artist"], right_on=["main_artist"], how="left")
    dfcounttracksranksnumenddatesgrptimesYearDayMonth = dfcounttracksranksnumenddatesgrptimesYear.merge(df_EndDate_YearMonthDaythecountryMaxDay, left_on=["main_artist"], right_on=["main_artist"], how="left")
    dfcounttracksranksnumenddatesgrptimesYearDayMonthfirstrank = dfcounttracksranksnumenddatesgrptimesYearDayMonth.merge(dfartistsfirstdate, left_on=["main_artist"], right_on=["main_artist"], how="left")

    
    return dfcounttracksranksnumenddatesgrptimesYearDayMonthfirstrank

In [3]:
todays_date = date.today()

In [4]:
df = pd.read_csv("Classification/all_files_ZAv1.csv")
df_za = getthecounts(df,"ZA", todays_date)

C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Year_"+thecountry] = dfartists["End Date"].apply(lambda x : x.split("-")[0])
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Month_"+thecountry] = dfartists["End Date"].apply(lambda x : x.split("-")[1])
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Day_"+thecountry] = dfartists["End Date"].apply(lambda x : x.split("-")[2])
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Year_"+thecountry] = dfartists["EndDate_Year_"+thecountry].astype(int)
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Month_"+thecountry] = dfartists["EndDate_Month_"+thecountry].astype(int)
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Day_"+thecountry] = dfartists["EndDate_Day_"+thecountry].astype(int)
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDateDt_"+thecountry] = dfartists[["EndDate_Year_"+thecountry, "EndDate_Month_"+thecountry, "EndDate_Day_"+thecountry]].apply(lambda x : date(x["EndDate_Year_"+thecountry], x["EndDate_Month_"+thecountry], x["EndDate_Day_"+thecountry]), axis=1)

In [5]:
df_za

,main_artist,max_rank_ZA,min_rank_ZA,#_songs_ZA,#_dates_ZA,IsGirlGroup_ZA,IsBoyGroup_ZA,IsMixedGroup_ZA,Earliest_EndDateDt_ZA,Longest_Charting_TimeDays_ZA,Latest_EndDateDt_ZA,Shortest_Charting_TimeDays_ZA,MinEndDate_Year_ZA,MinEndDate_Month_ZA,MinEndDate_Day_ZA,MaxEndDate_Year_ZA,MaxEndDate_Month_ZA,MaxEndDate_Day_ZA,first_artist_rank_ZA
0,$,183,5,15,22,False,False,False,2024-02-15,505,2024-08-08,330,2024,2,2,2024,8,30,38
1,$NOT,194,194,1,1,False,False,False,2022-02-10,1240,2022-02-10,1240,2022,2,10,2022,2,10,194
2,$uicideboy$,182,182,1,1,False,False,False,2021-10-07,1366,2021-10-07,1366,2021,10,7,2021,10,7,182
3,015 MusiQ & Van City MusiQ,185,41,1,16,False,False,False,2024-10-17,260,2025-01-30,155,2024,1,2,2025,12,31,111
4,031CHOPPA,168,128,2,2,False,False,False,2022-09-08,1030,2024-10-24,253,2022,9,8,2024,10,24,128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1291,salem ilese,186,53,1,12,False,False,False,2020-09-10,1758,2020-11-26,1681,2020,9,1,2020,11,29,107
1292,sombr,199,87,2,9,False,False,False,2025-05-08,57,2025-07-03,1,2025,5,3,2025,7,29,178
1293,the King will come,192,153,1,2,False,False,False,2023-07-20,715,2023-07-27,708,2023,7,20,2023,7,27,192
1294,twocolors,197,196,1,2,False,False,False,2021-01-14,1632,2021-01-21,1625,2021,1,14,2021,1,21,196
1295,uLazi,197,15,2,33,False,False,False,2022-07-28,1072,2024-01-04,547,2022,1,1,2024,12,31,197

In [6]:
df = pd.read_csv("Classification/all_files_gbv1.csv")
df_gb = getthecounts(df,"GB", todays_date)

C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Year_"+thecountry] = dfartists["End Date"].apply(lambda x : x.split("-")[0])
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Month_"+thecountry] = dfartists["End Date"].apply(lambda x : x.split("-")[1])
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Day_"+thecountry] = dfartists["End Date"].apply(lambda x : x.split("-")[2])
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Year_"+thecountry] = dfartists["EndDate_Year_"+thecountry].astype(int)
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Month_"+thecountry] = dfartists["EndDate_Month_"+thecountry].astype(int)
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Day_"+thecountry] = dfartists["EndDate_Day_"+thecountry].astype(int)
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDateDt_"+thecountry] = dfartists[["EndDate_Year_"+thecountry, "EndDate_Month_"+thecountry, "EndDate_Day_"+thecountry]].apply(lambda x : date(x["EndDate_Year_"+thecountry], x["EndDate_Month_"+thecountry], x["EndDate_Day_"+thecountry]), axis=1)

In [7]:
df = pd.read_csv("Classification/all_files_krv1.csv")
df_kr = getthecounts(df,"KR", todays_date)

C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Year_"+thecountry] = dfartists["End Date"].apply(lambda x : x.split("-")[0])
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Month_"+thecountry] = dfartists["End Date"].apply(lambda x : x.split("-")[1])
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Day_"+thecountry] = dfartists["End Date"].apply(lambda x : x.split("-")[2])
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Year_"+thecountry] = dfartists["EndDate_Year_"+thecountry].astype(int)
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Month_"+thecountry] = dfartists["EndDate_Month_"+thecountry].astype(int)
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Day_"+thecountry] = dfartists["EndDate_Day_"+thecountry].astype(int)
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDateDt_"+thecountry] = dfartists[["EndDate_Year_"+thecountry, "EndDate_Month_"+thecountry, "EndDate_Day_"+thecountry]].apply(lambda x : date(x["EndDate_Year_"+thecountry], x["EndDate_Month_"+thecountry], x["EndDate_Day_"+thecountry]), axis=1)

In [8]:
df = pd.read_csv("Classification/all_files_inv1.csv")
df_in = getthecounts(df,"IN", todays_date)

C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Year_"+thecountry] = dfartists["End Date"].apply(lambda x : x.split("-")[0])
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Month_"+thecountry] = dfartists["End Date"].apply(lambda x : x.split("-")[1])
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Day_"+thecountry] = dfartists["End Date"].apply(lambda x : x.split("-")[2])
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Year_"+thecountry] = dfartists["EndDate_Year_"+thecountry].astype(int)
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Month_"+thecountry] = dfartists["EndDate_Month_"+thecountry].astype(int)
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Day_"+thecountry] = dfartists["EndDate_Day_"+thecountry].astype(int)
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDateDt_"+thecountry] = dfartists[["EndDate_Year_"+thecountry, "EndDate_Month_"+thecountry, "EndDate_Day_"+thecountry]].apply(lambda x : date(x["EndDate_Year_"+thecountry], x["EndDate_Month_"+thecountry], x["EndDate_Day_"+thecountry]), axis=1)

In [9]:
df = pd.read_csv("Classification/all_files_globalv1.csv")
df_global = getthecounts(df,"Global", todays_date)

C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Year_"+thecountry] = dfartists["End Date"].apply(lambda x : x.split("-")[0])
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Month_"+thecountry] = dfartists["End Date"].apply(lambda x : x.split("-")[1])
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Day_"+thecountry] = dfartists["End Date"].apply(lambda x : x.split("-")[2])
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Year_"+thecountry] = dfartists["EndDate_Year_"+thecountry].astype(int)
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Month_"+thecountry] = dfartists["EndDate_Month_"+thecountry].astype(int)
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDate_Day_"+thecountry] = dfartists["EndDate_Day_"+thecountry].astype(int)
C:\Users\lkhum\AppData\Local\Temp\ipykernel_32116\2181284358.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfartists["EndDateDt_"+thecountry] = dfartists[["EndDate_Year_"+thecountry, "EndDate_Month_"+thecountry, "EndDate_Day_"+thecountry]].apply(lambda x : date(x["EndDate_Year_"+thecountry], x["EndDate_Month_"+thecountry], x["EndDate_Day_"+thecountry]), axis=1)

In [10]:
df_global.drop(['Earliest_EndDateDt_Global', 'Latest_EndDateDt_Global'],inplace=True,axis=1)
df_za.drop(['Earliest_EndDateDt_ZA', 'Latest_EndDateDt_ZA'],inplace=True,axis=1)
df_gb.drop(['Earliest_EndDateDt_GB', 'Latest_EndDateDt_GB'],inplace=True,axis=1)
df_kr.drop(['Earliest_EndDateDt_KR', 'Latest_EndDateDt_KR'],inplace=True,axis=1)
df_in.drop(['Earliest_EndDateDt_IN', 'Latest_EndDateDt_IN'],inplace=True,axis=1)

In [11]:
df_globalza = df_global.merge(df_za, left_on=["main_artist"], right_on=["main_artist"], how="outer")
df_globalzagb = df_globalza.merge(df_gb, left_on=["main_artist"], right_on=["main_artist"], how="outer")
df_globalzagbkr = df_globalzagb.merge(df_kr, left_on=["main_artist"], right_on=["main_artist"], how="outer")
df_globalzagbkrin = df_globalzagbkr.merge(df_in, left_on=["main_artist"], right_on=["main_artist"], how="outer")

In [12]:
df_globalza.shape, df_globalzagb.shape, df_globalzagbkr.shape, df_globalzagbkrin.shape

((2119, 33), (2624, 49), (3038, 65), (3556, 81))

In [13]:
df_za.columns

Index(['main_artist', 'max_rank_ZA', 'min_rank_ZA', '#_songs_ZA', '#_dates_ZA',
       'IsGirlGroup_ZA', 'IsBoyGroup_ZA', 'IsMixedGroup_ZA',
       'Longest_Charting_TimeDays_ZA', 'Shortest_Charting_TimeDays_ZA',
       'MinEndDate_Year_ZA', 'MinEndDate_Month_ZA', 'MinEndDate_Day_ZA',
       'MaxEndDate_Year_ZA', 'MaxEndDate_Month_ZA', 'MaxEndDate_Day_ZA',
       'first_artist_rank_ZA'],
      dtype='object')

In [14]:
df_globalzagbkrin = df_globalzagbkrin.fillna(0)

In [15]:
df_globalzagbkrin.to_csv("Classification/globalzagbkrin_counts.csv", index=False)

In [16]:
df_kr

,main_artist,max_rank_KR,min_rank_KR,#_songs_KR,#_dates_KR,IsGirlGroup_KR,IsBoyGroup_KR,IsMixedGroup_KR,Longest_Charting_TimeDays_KR,Shortest_Charting_TimeDays_KR,MinEndDate_Year_KR,MinEndDate_Month_KR,MinEndDate_Day_KR,MaxEndDate_Year_KR,MaxEndDate_Month_KR,MaxEndDate_Day_KR,first_artist_rank_KR
0,Damons year,200,8,4,144,False,False,False,1044,1,2022,1,1,2025,12,31,181
1,#Annyeong,145,145,1,1,False,False,False,22,22,2025,6,12,2025,6,12,145
2,$,192,31,23,20,False,False,False,505,295,2024,2,2,2024,9,29,75
3,(G)I-DLE,199,1,25,141,True,False,False,1597,267,2021,1,1,2024,12,31,36
4,*NSYNC,172,119,1,4,False,False,False,330,309,2024,8,8,2024,8,29,121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
769,toigo,198,86,2,9,False,False,False,925,869,2022,1,2,2023,12,29,86
770,tripleS,196,17,4,51,True,False,False,974,36,2022,1,1,2025,12,30,120
771,tuki.,198,79,2,56,False,False,False,421,1,2024,1,1,2025,12,31,139
772,wave to earth,200,133,2,42,False,False,False,379,8,2024,1,1,2025,12,31,199
773,yung kai,177,26,1,28,False,False,False,190,1,2024,1,1,2025,12,30,177

In [18]:
mapgrp = {False:0, True:1}

In [20]:
df_global["IsGirlGroup_Global"] = df_global["IsGirlGroup_Global"].apply(lambda x : mapgrp[x])
df_za["IsGirlGroup_ZA"] = df_za["IsGirlGroup_ZA"].apply(lambda x : mapgrp[x])
df_gb["IsGirlGroup_GB"] = df_gb["IsGirlGroup_GB"].apply(lambda x : mapgrp[x])
df_kr["IsGirlGroup_KR"] = df_kr["IsGirlGroup_KR"].apply(lambda x : mapgrp[x])
df_in["IsGirlGroup_IN"] = df_in["IsGirlGroup_IN"].apply(lambda x : mapgrp[x])

df_global["IsBoyGroup_Global"] = df_global["IsBoyGroup_Global"].apply(lambda x : mapgrp[x])
df_za["IsBoyGroup_ZA"] = df_za["IsBoyGroup_ZA"].apply(lambda x : mapgrp[x])
df_gb["IsBoyGroup_GB"] = df_gb["IsBoyGroup_GB"].apply(lambda x : mapgrp[x])
df_kr["IsBoyGroup_KR"] = df_kr["IsBoyGroup_KR"].apply(lambda x : mapgrp[x])
df_in["IsBoyGroup_IN"] = df_in["IsBoyGroup_IN"].apply(lambda x : mapgrp[x])

df_global["IsMixedGroup_Global"] = df_global["IsMixedGroup_Global"].apply(lambda x : mapgrp[x])
df_za["IsMixedGroup_ZA"] = df_za["IsMixedGroup_ZA"].apply(lambda x : mapgrp[x])
df_gb["IsMixedGroup_GB"] = df_gb["IsMixedGroup_GB"].apply(lambda x : mapgrp[x])
df_kr["IsMixedGroup_KR"] = df_kr["IsMixedGroup_KR"].apply(lambda x : mapgrp[x])
df_in["IsMixedGroup_IN"] = df_in["IsMixedGroup_IN"].apply(lambda x : mapgrp[x])

In [25]:
df_in.columns

Index(['main_artist', 'max_rank_IN', 'min_rank_IN', '#_songs_IN', '#_dates_IN',
       'IsGirlGroup_IN', 'IsBoyGroup_IN', 'IsMixedGroup_IN',
       'Longest_Charting_TimeDays_IN', 'Shortest_Charting_TimeDays_IN',
       'MinEndDate_Year_IN', 'MinEndDate_Month_IN', 'MinEndDate_Day_IN',
       'MaxEndDate_Year_IN', 'MaxEndDate_Month_IN', 'MaxEndDate_Day_IN',
       'first_artist_rank_IN'],
      dtype='object')

In [27]:
df_global.columns = ['main_artist', 'max_rank', 'min_rank', 'num_songs','num_dates', 'IsGirlGroup', 'IsBoyGroup','IsMixedGroup', 'Longest_Charting_TimeDays','Shortest_Charting_TimeDays', 'MinEndDate_Year','MinEndDate_Month', 'MinEndDate_Day', 'MaxEndDate_Year', 'MaxEndDate_Month', 'MaxEndDate_Day', 'first_artist_rank']
df_za.columns = ['main_artist', 'max_rank', 'min_rank', 'num_songs','num_dates', 'IsGirlGroup', 'IsBoyGroup','IsMixedGroup', 'Longest_Charting_TimeDays','Shortest_Charting_TimeDays', 'MinEndDate_Year','MinEndDate_Month', 'MinEndDate_Day', 'MaxEndDate_Year', 'MaxEndDate_Month', 'MaxEndDate_Day', 'first_artist_rank']
df_gb.columns = ['main_artist', 'max_rank', 'min_rank', 'num_songs','num_dates', 'IsGirlGroup', 'IsBoyGroup','IsMixedGroup', 'Longest_Charting_TimeDays','Shortest_Charting_TimeDays', 'MinEndDate_Year','MinEndDate_Month', 'MinEndDate_Day', 'MaxEndDate_Year', 'MaxEndDate_Month', 'MaxEndDate_Day', 'first_artist_rank']
df_kr.columns = ['main_artist', 'max_rank', 'min_rank', 'num_songs','num_dates', 'IsGirlGroup', 'IsBoyGroup','IsMixedGroup', 'Longest_Charting_TimeDays','Shortest_Charting_TimeDays', 'MinEndDate_Year','MinEndDate_Month', 'MinEndDate_Day', 'MaxEndDate_Year', 'MaxEndDate_Month', 'MaxEndDate_Day', 'first_artist_rank']
df_in.columns = ['main_artist', 'max_rank', 'min_rank', 'num_songs','num_dates', 'IsGirlGroup', 'IsBoyGroup','IsMixedGroup', 'Longest_Charting_TimeDays','Shortest_Charting_TimeDays', 'MinEndDate_Year','MinEndDate_Month', 'MinEndDate_Day', 'MaxEndDate_Year', 'MaxEndDate_Month', 'MaxEndDate_Day', 'first_artist_rank']

df_global.to_csv("ChartsAnalysis/df_global.csv", index=False)
df_za.to_csv("ChartsAnalysis/df_za.csv", index=False)
df_gb.to_csv("ChartsAnalysis/df_gb.csv", index=False)
df_kr.to_csv("ChartsAnalysis/df_kr.csv", index=False)
df_in.to_csv("ChartsAnalysis/df_in.csv", index=False)

In [29]:
df_global.shape, df_za.shape, df_gb.shape, df_kr.shape, df_in.shape

((1449, 17), (1296, 17), (1296, 17), (774, 17), (815, 17))

In [31]:
df_kr

,main_artist,max_rank,min_rank,num_songs,num_dates,IsGirlGroup,IsBoyGroup,IsMixedGroup,Longest_Charting_TimeDays,Shortest_Charting_TimeDays,MinEndDate_Year,MinEndDate_Month,MinEndDate_Day,MaxEndDate_Year,MaxEndDate_Month,MaxEndDate_Day,first_artist_rank
0,Damons year,200,8,4,144,0,0,0,1044,1,2022,1,1,2025,12,31,181
1,#Annyeong,145,145,1,1,0,0,0,22,22,2025,6,12,2025,6,12,145
2,$,192,31,23,20,0,0,0,505,295,2024,2,2,2024,9,29,75
3,(G)I-DLE,199,1,25,141,1,0,0,1597,267,2021,1,1,2024,12,31,36
4,*NSYNC,172,119,1,4,0,0,0,330,309,2024,8,8,2024,8,29,121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
769,toigo,198,86,2,9,0,0,0,925,869,2022,1,2,2023,12,29,86
770,tripleS,196,17,4,51,1,0,0,974,36,2022,1,1,2025,12,30,120
771,tuki.,198,79,2,56,0,0,0,421,1,2024,1,1,2025,12,31,139
772,wave to earth,200,133,2,42,0,0,0,379,8,2024,1,1,2025,12,31,199
773,yung kai,177,26,1,28,0,0,0,190,1,2024,1,1,2025,12,30,177

In [33]:
# trackAppearanceCount, artistAppearanceCount, source

In [35]:
# df = pd.read_csv("Classification/all_files_krv1.csv")

In [37]:
# thkrdfs = df[["main_artist", "track_name", "rank"]].groupby(["main_artist", "rank"]).count().reset_index()

In [39]:
# numones = thkrdfs[thkrdfs["rank"]==1]

In [41]:
# numones